### ISSUE TITLE
落ちる問題１

### ISSUE THREAD

**Issue by rockymanobi** [divea-devteam/SIZKANIC_Python#1]
ここにエラーを貼り付けるんだ！

**Comment by NakanoYudou** [comment]
はい

**Comment by NakanoYudou** [comment]
↓プログラムが起動するたびに表示されラグの原因になっているエラーです
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started

↓ここからのエラーが原因でプログラムが止まります
Traceback (most recent call last):
  File "main_2.py", line 41, in <module>
    mn.main()
  File "main_2.py", line 16, in main
    cnd.create_noise_data() #騒音情報作成メソッド
  File "/home/pi/Desktop/software/create_noise_data_5.py", line 42, in create_noise_data
    data = stream.read(chunk)
  File "/usr/lib/pymodules/python2.7/pyaudio.py", line 564, in read
    return pa.read_stream(self._stream, num_frames)
IOError: [Errno Input overflowed] -9981
